version: '3.8'  # Specify the version or omit this line

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase  # Ensure db is referenced correctly

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  db:
    image: mongo
    ports:
      - "27017:27017"

  adminer:  # Define the adminer service
    image: adminer
    ports:
      - "8080:8080"  # Expose Adminer on port 8080
